name: daily-trends

on:
  workflow_dispatch:
  schedule:
    - cron: "20 6 * * *"  # 06:20 UTC diario (ajusta si quieres)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci || npm i

      - name: Generar tendencias de productos (IA)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          AMAZON_TAG_ES: ${{ secrets.AMAZON_TAG_ES }}
          SHEIN_PID: "5798341419"
        run: npm run products:daily

      - name: Build
        run: npm run build

      - name: Commit & push
        if: ${{ success() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: daily AI products $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
